spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  liquibase:
    contexts: prod

