spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_service?tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate





#server:
#  error:
#      include-message: always