spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
  jpa:
    show-sql: true
  liquibase:
    contexts: dev
  h2:
    console:
      enabled: true
      path: /konsola